spring:
  datasource:
    url: ${db.cloud.url}
    username: ${db.cloud.username}
    password: ${db.cloud.password}
    hikari:
      schema: auth
  flyway:
    default-schema: auth
  application:
    name: auth-service
server:
  error:
    include-message: always

mycloud:
  security:
    public-endpoints:
      - /login